name = "BammannChiesaJohnsons"
uuid = "056ed34d-f5e1-4b0f-b3f6-c7e5e8ee168e"
authors = ["Joby M. Anthony III", "Julian Tse Lop Kun"]
version = "0.0.0-dev"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "1"
Test = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
